# -*- coding: utf-8 -*-
"""주식 수급분석.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eB4x1xJe7i84D1S7IG9zr53N9nMq-l1_
"""

!pip install pykrx

def stock_chart(start,end,ticker):
  import pandas as pd
  import numpy as np
  import plotly.graph_objects as go
  from pykrx import stock
  from plotly.subplots import make_subplots
  
  stock_name = stock.get_market_ticker_name(ticker) 
  value = stock.get_market_ohlcv_by_date(fromdate=start,todate=end,ticker=ticker).reset_index()
  volume = stock.get_market_trading_value_by_date(fromdate=start,todate=end,ticker=ticker).reset_index()
  df = volume.join(value.set_index('날짜')['종가'], on = '날짜').iloc[:,[0,1,4,6]]
  df['외국인누적'] = df['외국인합계'].copy()
  df['기관누적'] = df['기관합계'].copy()

  for i in range(0,len(df.index)-1):
    df['외국인누적'][i+1] = df['외국인누적'][i] + df['외국인합계'][i+1] 
    df['기관누적'][i+1] = df['기관누적'][i] + df['기관합계'][i+1]
 
  fig = make_subplots(specs=[[{'secondary_y':True}]])
  fig.add_trace(go.Scatter(x = df['날짜'], y = df['외국인누적'], name = '외국인누적', mode = 'lines', line = dict(color = '#173f5f', width = 1.5)), 
                  secondary_y = False)
  fig.add_trace(go.Scatter(x = df['날짜'], y = df['기관누적'], name = '기관누적', mode = 'lines', line = dict(color = '#3ca2a3', width = 1.5)),
                  secondary_y = False)
  fig.add_trace(go.Scatter( x = df['날짜'], y = df['종가'], name = '종가', mode = 'lines', line = dict(color = '#ed553b', width = 1.5)),
                  secondary_y = True)
  fig.update_layout(
        title = stock_name+' 누적수급 및 종가',
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=0.93),
        autosize = True,
        showlegend = True,
        font = dict(size = 10, color = '#000000'),
        plot_bgcolor = 'white',
        xaxis = dict(title = '년도', showline = True, showgrid = True, showticklabels = True, 
                    linecolor = '#000000', linewidth = 1,ticks = 'outside'),
        yaxis = dict(title = '기관 및 외국인 수급 누적', showline = True, showgrid = True, showticklabels = True, 
                    linecolor = '#000000', linewidth = 1,ticks = 'outside'),     
        yaxis2 = dict(title = '종가', showline = True, showgrid = True, showticklabels = True, 
                      linecolor = '#000000', linewidth = 1,ticks = 'outside')
        )
  fig.show()

tickers = ['000660','096770','004020','005490','005380','008770','375500','000270','034730','034220','004000','011780',
           '071050','018260','009150','011170','005930']

for ticker in tickers:
  stock_chart('20010101','20211221',ticker)